import { Client } from "@modelcontextprotocol/client";
import { InMemoryTransport } from "@modelcontextprotocol/server";
import { serve } from "@hono/node-server";
import { createMcp } from "../src/mcp.ts";
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync,mkdirSync,writeFileSync,rmSync,realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID, createHash } from "node:crypto";
import { createService } from "../src/service.ts";
import { Peers,PeerError,type PeerTransport } from "../src/peers.ts";
import { deviceSettings } from "../src/devices.ts";
import type { Project, CatalogSnapshot } from "../src/contracts.ts";

test("connected routing preserves exact owner, scope, replay and native eligibility",async()=>{
 const dir=realpathSync(mkdtempSync(join(tmpdir(),"agentklar-cross-route-"))),a=join(dir,"a"),b=join(dir,"b");mkdirSync(a);
 const git=(...args:string[])=>execFileSync("git",args,{encoding:"utf8",stdio:["ignore","pipe","ignore"]}).trim();
 git("-C",a,"init");git("-C",a,"config","user.email","test@example.test");git("-C",a,"config","user.name","Test");writeFileSync(join(a,"one.txt"),"one");git("-C",a,"add",".");git("-C",a,"commit","-m","base");git("clone",a,b);
 const sourcePort=27000+Math.floor(Math.random()*4000),ownerPort=sourcePort+1;
 let localExhausted=true,remoteExhausted=false,offline=false,loseAck=false,localStarts=0,remoteStarts=0,metadataCalls=0;
 let gate:Promise<void>|undefined;
 const snapshots: {remote:boolean;snapshot:CatalogSnapshot}[]=[];
 const reader=(remote:boolean)=>async(project:Project):Promise<CatalogSnapshot>=>{if(gate&&(!remote||project.name==="delayed-owner"))await gate;if(!remote&&project.name==="failure")throw new Error("local metadata unavailable");const snapshot:CatalogSnapshot={projectId:project.id,checkedAt:new Date().toISOString(),harnesses:[{harness:"codex",modelsStatus:"available",modelsMessage:null,modelsTruncated:false,models:[{id:"gpt-6.1-sol",name:"Sol",description:"",resolvedModel:null,isDefault:true,inputModalities:["text","image"]}],quota:{status:"available",message:null,ordinaryUsageAllowed:true,buckets:[{id:"codex",name:null,normalModel:null,primary:{usedPercent:(remote?remoteExhausted:localExhausted)?100:10,windowDurationMins:300,resetsAt:Date.now()/1000+300},secondary:null,spendControlReached:false}]}}]};snapshots.push({remote,snapshot});return snapshot;};
 const owner=createService(join(dir,"owner"),ownerPort,(_,run,__,cb)=>{remoteStarts++;queueMicrotask(()=>{cb.update({state:"completed",result:"done"});cb.done();});return {stop(){},closed:Promise.resolve()};},process.execPath,null,reader(true));
 const call=(s:typeof owner,port:number)=>async(path:string,method="GET",body?:unknown)=>{const r=await s.app.request(`http://127.0.0.1:${port}${path}`,{method,headers:{Authorization:`Bearer ${s.bearer}`,"Content-Type":"application/json"},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};
 const transport:PeerTransport=async(_,request)=>{if(request.operation==="routing")metadataCalls++;if(offline)throw new PeerError("offline",503);const result=await call(owner,ownerPort)("/api/peer","POST",request);if(loseAck&&request.operation==="start"){loseAck=false;throw new PeerError("lost acknowledgement",503);}return result;};
 const local=createService(join(dir,"local"),sourcePort,(_,run,__,cb)=>{localStarts++;queueMicrotask(()=>{cb.update({state:"completed",result:"local done"});cb.done();});return {stop(){},closed:Promise.resolve()};},process.execPath,null,reader(false),undefined,undefined,undefined,undefined,null,undefined,null,transport);
 const http=serve({fetch:local.app.fetch,hostname:"127.0.0.1",port:sourcePort});const mcp=createMcp(`http://127.0.0.1:${sourcePort}`,local.bearer);const client=new Client({name:"routing-wire-test",version:"1"});const [clientWire,serverWire]=InMemoryTransport.createLinkedPair();await mcp.connect(serverWire);await client.connect(clientWire);
 const tool=async(name:string,args:Record<string,unknown>)=>{const result=await client.callTool({name,arguments:args});assert.ok(!result.isError,JSON.stringify(result));return JSON.parse((result.content as {text:string}[])[0].text);};
 const project=(s:typeof owner,path:string)=>{const p:Project={id:randomUUID(),name:"fixture",path,roles:[],preference:"balanced",createdAt:"now"};s.store.saveProject(p);return p;};
 try{
 const lp=project(local,a),rp=project(owner,b),ld=deviceSettings(local.store.db).device,od=deviceSettings(owner.store.db).device;
 const op=new Peers(owner.store,od,call(owner,ownerPort));const grant=op.grant({sourceDeviceId:ld.id,projectId:rp.id});const peers=new Peers(local.store,ld,call(local,sourcePort),transport);
 const mapping=peers.saveConnection({label:"Owner",deviceId:od.id,sshHost:"fixture",command:"agentklar",projectId:lp.id,remoteProjectId:rp.id,grantId:grant.id,grantToken:grant.token});
 const request=call(local,sourcePort);const advice=(body:unknown)=>request(`/api/projects/${lp.id}/recommend`,"POST",body);
 const input={projectId:lp.id,prompt:"small task",idempotencyKey:"auto",workspace:"worktree",routing:{complexity:"standard"}};
 const suitable={body:await tool("recommend_worker",{projectId:lp.id,workspace:"worktree",deviceScope:"connected"})};assert.equal(suitable.body.choice.device.peerId,mapping.id);assert.equal(localStarts+remoteStarts,0);
 loseAck=true;const started={status:202,body:await tool("task_start",{...input,routing:{...input.routing,deviceScope:"connected"}})};assert.equal(started.status,202);assert.equal(started.body.ownerDeviceId,od.id);assert.equal(started.body.connection,"unknown");assert.equal(started.body.routing.selected.model,"gpt-6.1-sol");
 const beta21Hash=createHash("sha256").update(JSON.stringify({projectId:lp.id,prompt:input.prompt,idempotencyKey:input.idempotencyKey,readOnly:false,routing:{complexity:"standard",requiresImages:false,taskType:"coding"},workspace:"worktree"})).digest("hex");assert.equal(peers.existing(lp.id,input.idempotencyKey)!.launchHash,beta21Hash);
 for(let i=0;i<100&&remoteStarts===0;i++)await new Promise(r=>setTimeout(r,10));assert.equal(remoteStarts,1);assert.equal(localStarts,0);const observed=await tool("run_status",{runId:started.body.id});assert.equal(observed.ownerDeviceId,od.id);assert.equal(observed.routing.selected.device.peerId,mapping.id);
 local.store.db.prepare("DELETE FROM peer_connections WHERE id=?").run(mapping.id);local.store.saveProject({...lp,preference:"economical"});const replay=await request("/api/tasks/start","POST",{...input,routing:{...input.routing,deviceScope:"connected"}});assert.equal(replay.body.id,started.body.id);assert.equal(remoteStarts,1);
 const mapping2=peers.saveConnection({label:"Owner2",deviceId:od.id,sshHost:"fixture",command:"agentklar",projectId:lp.id,remoteProjectId:rp.id,grantId:grant.id,grantToken:grant.token});
 assert.equal((await advice({workspace:"project"})).body.choice,null);assert.equal((await advice({workspace:"worktree",deviceScope:"local"})).body.choice,null);
 offline=true;assert.equal((await advice({workspace:"worktree"})).body.choice,null);offline=false;
 remoteExhausted=true;for(const x of snapshots.filter(x=>x.remote))x.snapshot.harnesses[0]!.quota.buckets[0]!.primary!.usedPercent=100;assert.equal((await advice({workspace:"worktree"})).body.choice,null);remoteExhausted=false;for(const x of snapshots.filter(x=>x.remote))x.snapshot.harnesses[0]!.quota.buckets[0]!.primary!.usedPercent=10;
 writeFileSync(join(b,"new.txt"),"new");git("-C",b,"config","user.email","test@example.test");git("-C",b,"config","user.name","Test");git("-C",b,"add",".");git("-C",b,"commit","-m","changed");assert.equal((await advice({workspace:"worktree"})).body.choice,null);git("-C",b,"reset","--hard",git("-C",a,"rev-parse","HEAD"));
 localExhausted=false;for(const x of snapshots.filter(x=>!x.remote))x.snapshot.harnesses[0]!.quota.buckets[0]!.primary!.usedPercent=10;local.store.saveProject({...lp,roles:[{id:"local",name:"Local",harness:"codex",model:"gpt-6.1-sol",responsibility:""},{id:"remote",name:"Remote",harness:"codex",model:"gpt-6.1-sol",responsibility:"",peerId:mapping2.id}]});
 assert.equal((await advice({roleId:"local",workspace:"worktree"})).body.choice.device.id,ld.id);assert.equal((await advice({roleId:"remote",workspace:"worktree",deviceScope:"local"})).body.choice.device.peerId,mapping2.id);
 const beforeDefault=metadataCalls;assert.equal((await advice({})).body.choice.device.id,ld.id);assert.equal(metadataCalls,beforeDefault);
 const before=metadataCalls;const localTask=await request("/api/tasks/start","POST",{...input,idempotencyKey:"local-folder",workspace:"project"});assert.equal(localTask.status,202);assert.equal(metadataCalls,before);
 for(let i=0;i<100&&localStarts===0;i++)await new Promise(r=>setTimeout(r,10));assert.equal(localStarts,1);await new Promise(r=>setTimeout(r,20));
 const omitted=await request("/api/tasks/start","POST",{...input,idempotencyKey:"default-folder",workspace:undefined});assert.equal(omitted.status,202,JSON.stringify(omitted.body));assert.equal(omitted.body.projectId,lp.id);assert.equal(omitted.body.ownerDeviceId,undefined);assert.equal(metadataCalls,before);
 const followLocal=await request("/api/tasks/start","POST",{...input,idempotencyKey:"local-review",workspace:undefined,readOnly:true,followUp:{runId:omitted.body.id,kind:"review"}});assert.equal(followLocal.status,202,JSON.stringify(followLocal.body));assert.equal(followLocal.body.ownerDeviceId,undefined);assert.equal(followLocal.body.workspace.path,a);assert.equal(metadataCalls,before);
 let release!:()=>void;gate=new Promise<void>(r=>release=r);
 const cpath=join(dir,"concurrent");git("clone",a,cpath);const concurrentProject=project(local,cpath);
 const concurrent={...input,projectId:concurrentProject.id,idempotencyKey:"race",routing:{complexity:"standard",deviceScope:"local"}};
 const one=request("/api/tasks/start","POST",concurrent),two=request("/api/tasks/start","POST",concurrent);await new Promise(r=>setTimeout(r,20));release();gate=undefined;
 const responses=await Promise.all([one,two]);assert.equal(responses[0].body.id,responses[1].body.id);assert.equal(local.store.runs().filter(r=>r.launchHash===local.store.run(responses[0].body.id)?.launchHash).length,1);
 const failPath=join(dir,"failure");git("clone",a,failPath);const failProject={...project(local,failPath),name:"failure"};local.store.saveProject(failProject);
 peers.saveConnection({label:"Owner failure fallback",deviceId:od.id,sshHost:"fixture",command:"agentklar",projectId:failProject.id,remoteProjectId:rp.id,grantId:grant.id,grantToken:grant.token});
 const failureAdvice=await request(`/api/projects/${failProject.id}/recommend`,"POST",{workspace:"worktree"});assert.equal(failureAdvice.body.choice.device.id,od.id);assert.match(failureAdvice.body.warnings.join(" "),/excluded/);
 const changedPath=join(dir,"changed");git("clone",a,changedPath);const changedProject=project(local,changedPath);
 gate=new Promise<void>(r=>release=r);const pending=request("/api/tasks/start","POST",{...input,projectId:changedProject.id,idempotencyKey:"settings-change",routing:{complexity:"standard",deviceScope:"local"}});await new Promise(r=>setTimeout(r,20));local.store.saveProject({...changedProject,preference:"best"});release();gate=undefined;assert.equal((await pending).status,409);
 const fakeBusy=(s:typeof owner,projectId:string)=>[1,2].map(n=>{const original=s.store.runs()[0]!;const run={...original,id:randomUUID(),projectId,state:"running" as const,workerPid:undefined,workspace:undefined};s.store.insertRun(run,`capacity-${projectId}-${n}`);return run;});
 const localBusy=fakeBusy(local,lp.id);assert.equal((await advice({workspace:"worktree"})).body.choice.device.id,od.id);for(const run of localBusy)local.store.saveRun({...run,state:"completed"});
 const ownerBusy=fakeBusy(owner,rp.id);assert.equal((await advice({workspace:"worktree"})).body.choice.device.id,ld.id);for(const run of ownerBusy)owner.store.saveRun({...run,state:"completed"});
 const delayedPath=join(dir,"delayed-owner");git("clone",a,delayedPath);const delayedOwner={...project(owner,delayedPath),name:"delayed-owner"};owner.store.saveProject(delayedOwner);const delayedGrant=op.grant({sourceDeviceId:ld.id,projectId:delayedOwner.id});
 gate=new Promise<void>(r=>release=r);const originalBase=git("-C",delayedPath,"rev-parse","HEAD"),priorStarts=remoteStarts;
 const pendingOwner=call(owner,ownerPort)("/api/peer","POST",{version:1,sourceDeviceId:ld.id,targetDeviceId:od.id,grantId:delayedGrant.id,token:delayedGrant.token,operation:"start",requestId:randomUUID(),baseCommit:originalBase,task:{prompt:"exact base",harness:"codex",model:"gpt-6.1-sol",readOnly:false,routingEvidence:started.body.routing}});
 await new Promise(r=>setTimeout(r,20));writeFileSync(join(delayedPath,"later.txt"),"later");git("-C",delayedPath,"config","user.email","test@example.test");git("-C",delayedPath,"config","user.name","Test");git("-C",delayedPath,"add",".");git("-C",delayedPath,"commit","-m","advanced during metadata");release();gate=undefined;
 const ownerRejected=await pendingOwner;assert.equal(ownerRejected.status,409);assert.match(ownerRejected.body.error,/HEAD changed/);assert.equal(remoteStarts,priorStarts);assert.equal(owner.store.runs().filter(r=>r.projectId===delayedOwner.id).length,0);
 // Unknown tool support must fail at the owner even when routing evidence is weaker.
 const capabilityStarts=remoteStarts;
 for(const stronger of ["task", "evidence"] as const){
  const evidence={...started.body.routing,...(stronger==="evidence"?{requiresTools:["web_search"]}:{})};
  const rejected=await call(owner,ownerPort)("/api/peer","POST",{version:1,sourceDeviceId:ld.id,targetDeviceId:od.id,grantId:grant.id,token:grant.token,operation:"start",requestId:randomUUID(),baseCommit:git("-C",b,"rev-parse","HEAD"),task:{prompt:"strict tool requirement",harness:"codex",model:"gpt-6.1-sol",readOnly:false,routing:{requiresTools:stronger==="task"?["web_search"]:[]},routingEvidence:evidence}});
  assert.equal(rejected.status,409,JSON.stringify(rejected.body));assert.match(rejected.body.error,/required worker tools/);
  assert.equal(remoteStarts,capabilityStarts);
 }
 // Preserve a source run's requirement unless the next task explicitly clears it.
 local.store.db.prepare("INSERT INTO peer_connections(id,data) VALUES(?,?)").run(mapping.id,JSON.stringify({...mapping,grantToken:grant.token}));
 const sourceRun=owner.store.run(observed.ownerRunId)!;
 owner.store.saveRun({...sourceRun,routing:{...sourceRun.routing!,requiresTools:["web_search"]}});
 await peers.status(started.body.id);
 const followInput={projectId:lp.id,prompt:"review source",readOnly:true,followUp:{runId:started.body.id,kind:"review"}};
 const inherited=await request("/api/tasks/start","POST",{...followInput,idempotencyKey:"inherited-tools"});
 assert.equal(inherited.status,202,JSON.stringify(inherited.body));assert.match(inherited.body.error,/No suitable model/);assert.equal(inherited.body.ownerRunId,undefined);assert.equal(remoteStarts,capabilityStarts);
 const inheritedRequest=JSON.parse(local.store.db.prepare("SELECT data FROM peer_dispatches WHERE id=?").get(inherited.body.id)!.data as string).request.task;
 assert.deepEqual(inheritedRequest.routing.requiresTools,["web_search"]);
 const cleared=await request("/api/tasks/start","POST",{...followInput,idempotencyKey:"explicit-clear-tools",routing:{requiresTools:[]}});
 assert.equal(cleared.status,202,JSON.stringify(cleared.body));assert.equal(cleared.body.connection,"observed",JSON.stringify(cleared.body));assert.equal(typeof cleared.body.ownerRunId,"string");
 const clearedRequest=JSON.parse(local.store.db.prepare("SELECT data FROM peer_dispatches WHERE id=?").get(cleared.body.id)!.data as string).request.task;
 assert.deepEqual(clearedRequest.routing.requiresTools,[]);
 await new Promise(resolve=>setTimeout(resolve,20));assert.equal(remoteStarts,capabilityStarts+1);
 assert.equal(owner.store.run(cleared.body.ownerRunId)!.routing?.requiresTools?.length??0,0);
 assert.equal((await request("/api/tasks/start","POST",{...input,idempotencyKey:"spoof",routingEvidence:started.body.routing})).status,400);
 }finally{await client.close();await mcp.close();await new Promise<void>(r=>http.close(()=>r()));await local.close();await owner.close();rmSync(dir,{recursive:true,force:true});}
});
